# MODEL PATHS

YOLO_DET_MODEL = r"E:\Krossmark\models\yolo26\yolo26m.pt"
HTSAT_MODEL = r"E:\Krossmark\models\htsat"  # <-- update if needed
QWEN_MODEL_NAME = "qwen3-vl:4b"
# VIDEO / INPUT

VIDEO_SOURCE = 0  # 0 = webcam
BURST_SECONDS = 3
AUDIO_SAMPLE_RATE = 48000
# DETECTION SETTINGS

CONF_THRESH = 0.3
IOU_THRESH = 0.5
YOLO_IMGSZ = 960
# VLM SETTINGS

VLM_COOLDOWN_FRAMES = 30

# THREAT SETTINGS

THREAT_LOW = 1
THREAT_HIGH = 4
# EVIDENCE

EVIDENCE_WINDOW = 15
CONFIRM_THRESHOLD = 0.6