# Generated by Django 6.0.2 on 2026-03-27 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_level', models.PositiveSmallIntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('group_intent', models.CharField(blank=True, default='', max_length=64)),
                ('scene_intent', models.CharField(blank=True, default='', max_length=64)),
                ('decision', models.CharField(blank=True, default='', max_length=64)),
                ('briefing', models.TextField(blank=True, default='')),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('actors', models.JSONField(blank=True, default=list)),
                ('video_context', models.JSONField(blank=True, default=dict)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BurstCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='bursts/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='bursts/audio/')),
                ('frame_count', models.PositiveIntegerField(default=0)),
                ('audio_sample_rate', models.PositiveIntegerField(default=48000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('device_type', models.CharField(choices=[('leaf', 'Leaf Node'), ('relay', 'Relay Node'), ('pi', 'Raspberry Pi'), ('command_center', 'Command Center'), ('sensor', 'Sensor Unit')], max_length=32)),
                ('api_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('location_tag', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('ack_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.analysisresult')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='burst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='surveillance.burstcapture'),
        ),
        migrations.AddField(
            model_name='burstcapture',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursts', to='surveillance.device'),
        ),
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_level', models.CharField(choices=[('leaf', 'Leaf'), ('intermediate', 'Intermediate'), ('pi', 'Pi'), ('command', 'Command')], default='leaf', max_length=24)),
                ('pir_triggered', models.BooleanField(default=False)),
                ('mic_triggered', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('sensor_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='surveillance.device')),
            ],
        ),
        migrations.AddField(
            model_name='burstcapture',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bursts', to='surveillance.triggerevent'),
        ),
    ]
