spring.application.name=krossmark-backend
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/krossmark_db
spring.datasource.username=krossmark
spring.datasource.password=krossmark

# Security
security.aes.key=80iM3AV86Lz2/9GI5J9dBiBRCE3jVZ+hveXdJw6JTeU=

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect